# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-12-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milanurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
