# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-12-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20191204_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milanurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
