# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-12-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20191204_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='milanurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
