# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-12-05 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_milanurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milanurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
